[package]
name = "fls"
version = "0.1.0"
authors = ["Ben Kimock <kimockb@gmail.com>"]
edition = "2018"
license = "GPL-3.0-or-later"

[dependencies]
veneer = { path = "../veneer" }
libc = "0.2"
unicode-width = "0.1"
git-version = "0.3"
tinyvec = { version = "1", features = ["alloc"] }
compiler_builtins = { version = "0.1", features = ["mem"] }

[profile.dev]
panic = "abort"

[profile.release]
debug = 2
lto = "fat"
panic = "abort"
