[package]
name = "fls"
version = "0.1.0"
authors = ["Ben Kimock <kimockb@gmail.com>"]
edition = "2018"
license = "GPL-3.0-or-later"

[dependencies]
libc = "0.2"
unicode-segmentation = "1.8"
sc = "0.2"
bitflags = "1"
git-version = "0.3"

[features]
link-libc = []

[profile.dev]
panic = "abort"

[profile.release]
debug = 1
lto = "fat"
panic = "abort"
