[package]
name = "fls"
version = "0.1.0"
authors = ["Ben Kimock <kimockb@gmail.com>"]
edition = "2018"

[dependencies]
termion = "1.0"
libc = "0.2"
smallvec = "0.6"

[profile.release]
lto = true
panic = 'abort'
