[package]
name = "fls"
version = "0.1.0"
authors = ["Ben Kimock <kimockb@gmail.com>"]
edition = "2018"
license = "GPL-3.0-or-later"

[dependencies]
libc = "0.2"
syscall = "0.2"
smallvec = {version = "0.6", default-features = false}
arrayvec = {version = "0.4", default-features = false}
wee_alloc = "0.4"
itoa = {version = "0.4", default-features = false}
libm = "0.1"
unicode-segmentation = "1.3"

[profile.release]
lto = "fat"
panic = "abort"
